Show test report after all tests

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -53,22 +53,14 @@ jobs:
 
       # no uv cache here because fresh install takes about 1 second
 
-      - name: Install dependencies
-        run: uv sync --group test
-
       - name: Run tests
         run: |
           mkdir reports/ || echo "Directory exists"
-          uv run coverage run -m pytest --junitxml=reports/junit/python${{ matrix.python-version }}.xml
-
-      - name: Show test results
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: reports/junit/*.xml
+          make test-ci PYTEST_ARGS="--junitxml=reports/junit/python${{ matrix.python-version }}.xml"
 
       - name: Upload coverage results
         uses: actions/upload-artifact@v6
+        if: always()
         with:
           name: coverage-${{ matrix.python-version }}-os-${{ matrix.os }}
           path: reports/*
@@ -84,6 +76,19 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v6
 
+      - name: Download all coverage reports
+        uses: actions/download-artifact@v7
+        with:
+          path: reports/
+          pattern: coverage-*
+          merge-multiple: true
+
+      - name: Show test results
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: reports/junit/*.xml
+
       - name: Set up Python ${{ env. DEFAULT_PYTHON }}
         uses: actions/setup-python@v6
         with:
@@ -96,20 +101,10 @@ jobs:
 
       # no uv cache here because fresh install takes about 1 second
 
-      - name: Install dependencies
-        run: uv sync --group test
-
-      - name: Download all coverage reports
-        uses: actions/download-artifact@v7
-        with:
-          path: reports/
-          pattern: coverage-*
-          merge-multiple: true
-
       - name: Generate coverate reports
         run: |
-          uv run coverage combine
-          uv run coverage xml -o reports/coverage.xml -i
+          uv run --group coverage combine
+          uv run --group coverage xml -o reports/coverage.xml -i
 
       - name: Coverage comment
         id: coverage
